version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
  
  webapp:
    container_name: rails_app
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - ADMIN_RAILS_PASSWORD=${ADMIN_RAILS_PASSWORD}
      - STANDARD_RAILS_PASSWORD=${STANDARD_RAILS_PASSWORD}
